name: flight
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.0.1
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  flutter_dotenv: ^5.0.2
  intl: any
  flutter_screenutil: ^5.7.0
  logger: ^2.2.0
  #data class
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  #functional programming
  dartz: ^0.10.1
  #routing
  auto_route: ^8.0.3
  #dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0
  #secure storage
  flutter_secure_storage: ^9.0.0
  #svg
  flutter_svg: ^2.0.5
  #screen util
  #cached
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  json_serializable: ^6.6.1
  connectivity_plus: ^6.0.2

  flutter_native_splash: ^2.4.0
  mockito: ^5.0.0
  bloc_test: ^9.1.7
  fl_chart: ^0.63.0
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.6.0
  sqflite: ^2.4.2
  path: ^1.9.1
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  #builders
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.1.4
  auto_route_generator: ^8.0.0
  freezed: ^2.3.2
  very_good_analysis: ^5.1.0
  mocktail: ^0.3.0

flutter_native_splash:
  color: "#8F7237"
  image: assets/icons/background1.png
  android_12:
    color: "#8F7237"
    image: assets/icons/background1.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env-dev
    - .env-staging
    - .env-prod
    - assets/icons/
    - assets/json/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
